# Configure global settings in this section.
global:
  name: consul
  # Bootstrap ACLs within Consul. This is highly recommended.
  acls:
    manageSystemACLs: true
  # Gossip encryption
  gossipEncryption:
    autoGenerate: true
# Configure your Consul servers in this section.
server:
  # Specify three servers that wait until all are healthy to bootstrap the Consul cluster.
  replicas: 1
  # Specify the resources that servers request for placement. These values will serve a large environment.
  resources:
    requests:
      memory: '100Mi'
      cpu: '100Mi'
    limits:
      memory: '100Mi'

  # If using Enterprise, reference the Kubernetes secret that holds your license here
# Configure Consul clients in this section
client:
  # Specify the resources that clients request for deployment.
  resources:
    requests:
      memory: '100Mi'
      cpu: '100Mi'
    limits:
      memory: '100Mi'
# Enable and configure the Consul UI.
ui:
  enabled: true
# Enable Consul connect pod injection
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
